INSERT INTO post (title, category, view_count, like_count, content, images)
VALUES ('달걀 삶기', 'cooking', 0, 0,
        '["1. 냄비, 달걀, 물을 준비합니다.",
        "2. 냄비에 물을 붓습니다.",
        "3. 물이 담겨진 냄비에 달걀을 하나씩 넣습니다.",
        "4. 잠겨있던 가스밸브를 왼쪽(반시계방향)으로 돌려 엽니다.",
        "5. 가스레인지 점화 손잡이를 왼쪽(반시계방향)으로 돌려 냄비에 불을 붙입니다.",
        "6. 약 10분 달걀을 삶습니다.",
        "7. 점화 손잡이를 오른쪽(시계방향)으로 돌려 불을 끕니다.",
        "8. 가스밸브를 오른쪽(시계방향)으로 돌려 잠급니다.",
        "9. 냄비 속 뜨거운 물을 하수구에 버립니다. 이때, 달걀을 떨어지지 않도록 주의합니다.",
        "10. 달걀 껍질이 잘 벗겨지도록 냄비 안에 차가운 물을 담아줍니다.",
        "11. 약 10분 간 차가운 물에 담가줍니다.",
        "12. 삶은 달걀 껍질을 벗기기 위해서 달걀을 하나 들어",
        "13. 그대로 탁자 모서리에 살살 내려칩니다.",
        "14. 깨진 부분부터 껍질을 벗기기 시작하여 달걀 껍질을 제거합니다.",
        "15. 껍질을 제거한 삶은 달걀을 맛있게 먹습니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/egg/egg_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_9.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_10.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_11.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_12.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_13.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_14.png",
        "https://storage.googleapis.com/example-gurdening-com/img/egg/egg_15.png"]'),
       ('햇반 조리', 'cooking', 0, 0,
        '["1. 전자레인지와 햇반을 준비합니다.",
            "2. 햇반을 잡고 점선 부분을 확인해줍니다.",
            "3. 확인한 점선 부분까지 비닐을 제거해줍니다.",
            "4. 전자레인지 손잡이를 잡고 문을 열어줍니다.",
            "5. 전자레인지 중앙에 햇반을 넣어줍니다.",
            "6. 전자레인지 문을 닫아주고 타이머를 2분으로 맞춰 조리합니다.",
            "7. 타이머가 다 될 때까지 기다려줍니다.",
            "8. 알람 소리가 들리면 다 되었다는 뜻입니다.",
            "9. 전자레인지 문을 엽니다.",
            "10. 조리된 뜨거운 햇반을 주의하며 전자레인지에서 꺼냅니다.",
            "11. 햇반의 포장지를 다 제거합니다.",
            "12. 숟가락을 준비합니다.",
            "13. 준비한 숟가락으로 햇반을 퍼, 맛있게 먹습니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_9.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_10.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_11.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_12.png",
        "https://storage.googleapis.com/example-gurdening-com/img/instant%20rice%20cooking/instant_rice_cooking_13.png"]'),
       ('캔따기', 'daily_life', 0, 0,
        '["1. 캔을 준비합니다.",
        "2. 한 손으로는 캔을 잡고 다른 손으로는 캔따개를 잡습니다.",
        "3. 캔따개를 잡은 손을 캔에서 ‘딱’ 소리가 날 때까지 몸 쪽으로 당겨줍니다.",
        "4. 캔따개를 다시 원위치로 돌려줍니다.",
        "5. 따진 캔을 잡고 음료수를 마십니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/Picking%20a%20can/Picking_a_can_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Picking%20a%20can/Picking_a_can_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Picking%20a%20can/Picking_a_can_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Picking%20a%20can/Picking_a_can_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Picking%20a%20can/Picking_a_can_5.png"]'),
       ('삼각김밥 뜯기', 'daily_life', 0, 0,
        '["1. 삼각깁밥을 준비합니다.",
        "2. 삼각김밥 가운데 절취선 따라 손잡이를 앞으로 당긴다.",
        "3. 뒤쪽까지 돌려서 뜯어낸다.",
        "4. 오른쪽 비닐 가장자리를 잡고 먼저 뜯어낸다.",
        "5. 나머지 왼쪽도 비닐을 잡아당겨 뜯는다.",
        "6. 포장지가 제거된 삼각김밥을 맛있게 먹는다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20triangle%20kimbap/Opening_a_triangle_kimbap_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20triangle%20kimbap/Opening_a_triangle_kimbap_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20triangle%20kimbap/Opening_a_triangle_kimbap_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20triangle%20kimbap/Opening_a_triangle_kimbap_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20triangle%20kimbap/Opening_a_triangle_kimbap_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20triangle%20kimbap/Opening_a_triangle_kimbap_6.png"]'),
       ('과자봉지 뜯기', 'daily_life', 0, 0,
        '["1. 먹을 과자를 하나 준비한다.",
        "2. (뜯는 곳) 바로 위를 한 손으로 잡는다. 다른 손은 바로 옆을 잡아 지지해준다.",
"3. 양 손을 비틀어 뜯고 오른손으로 뜯은 곳을 아래로 당겨 봉지 가장자리를 제거해준다.",
"4. 뜯은 부분에서 과자를 꺼낸다.",
"5. 꺼낸 과자를 맛있게 먹는다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20snack%20bag/Opening_a_snack_bag_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20snack%20bag/Opening_a_snack_bag_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20snack%20bag/Opening_a_snack_bag_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20snack%20bag/Opening_a_snack_bag_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20a%20snack%20bag/Opening_a_snack_bag_5.png"]'),
       ('우유팩 뜯기', 'daily_life', 0, 0,
        '["1. 우유를 준비합니다.",
        "2. (여는 곳)이라고 되어 있는 곳의 면을 양손으로 잡아 양 옆으로 벌립니다.",
"3. 편한 손으로 엄지와 검지를 집게 모양으로 만들어 뒤로 눌렀다가 꼬집듯이 나온 부분을 잡아줍니다.",
"4. 잡은 부분을 앞으로 쭉 당겨줍니다.",
"5. 열린 우유팩을 잡고 우유를 마셔줍니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/Opening%20the%20milk%20carton/Opening_the_milk_carton_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20the%20milk%20carton/Opening_the_milk_carton_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20the%20milk%20carton/Opening_the_milk_carton_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20the%20milk%20carton/Opening_the_milk_carton_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Opening%20the%20milk%20carton/Opening_the_milk_carton_5.png"]'),
       ('이닦기', 'cleanliness', 0, 0,
        '["1. 치약과 칫솔을 준비합니다.",
        "2. 치약을 칫솔을 다 덮을 정도로 짜줍니다.",
        "3. 칫솔을 입으로 가져갑니다.",
        "4. 칫솔로 아래 어금니부터 닦아줍니다.",
        "5. 칫솔을 들어 위 어금니를 닦아줍니다.",
        "6. 칫솔로 송곳니를 닦아줍니다.",
        "7. 반대편 이도 같은 방법으로 닦아줍니다.",
        "8. 모음 (ㅣ) 발음을 할 때처럼 이를 만들어주고 앞니를 닦아줍니다.",
"9. 칫솔을 가로로 두고 혀를 닦아줍니다.",
"10. 컵에 물을 받습니다.",
"11. 컵에 받은 물을 입에 머금습니다.",
"12. 물로 우물우물 입을 헹굽니다.",
"13. 헹군 물을 뱉어줍니다.",
"14. 사용한 칫솔을 물로 잘 닦아줍니다.",
"15. 사용한 도구들을 원래 자리에 놓습니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_9.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_10.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_11.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_12.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_13.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_14.png",
        "https://storage.googleapis.com/example-gurdening-com/img/brushing%20teeth/brushing_teeth_15.png"]'),
       ('손톱깎기', 'cleanliness', 0, 0,
        '["1. 손톱깎이를 준비합니다.",
        "2. 잘라야 할 손톱들을 확인합니다.",
        "3. 반대 손으로 손톱깎이를 잡습니다. 이때, 그림과 똑같이 손톱깎이를 잡아줍니다.",
        "4. 엄지부터 하얀 부분만 둥글게 잘라줍니다.",
        "5. 검지 손톱을 잘라줍니다.",
        "6. 중지 손톱을 잘라줍니다.",
        "7. 약지 손톱을 잘라줍니다.",
        "8. 새끼손가락 손톱을 잘라줍니다.",
        "9. 자른 손톱을 모아 잘 버려줍니다.",
        "10. 잘 깎았는지 손가락을 확인해줍니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_9.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Clipping%20nails/Clipping_nails_10.png"]'),
       ('연고 바르기', 'treatment', 0, 0,
        '["1. 상처가 난 부위(환부)를 잘 보이도록 준비합니다.",
        "2. 연고를 준비합니다.",
        "3. 포장을 제거합니다.",
        "4. 연고의 뚜껑을 잡고 돌려 열어줍니다.",
        "5. 뚜껑을 잡고 뾰족한 부분을 확인합니다.",
        "6. 뾰족한 부분이 아래로 가게 해줍니다.",
        "7. 뾰족한 부분을 연고가 나오는 입구로 가져가 구멍을 맞춰주고 꾹 눌러줍니다.",
        "8. 나오는 연고를 손에 적당량 묻혀줍니다.",
        "9. 상처 부위에 연고를 잘 발라줍니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/applying%20ointment/applying_ointment_9.png"]'),
       ('에어파스(스프레이) 사용하기', 'treatment', 0, 0,
        '["1. 아픈 부위(환부)를 잘 보이도록 준비합니다.",
        "2. 에어파스를 준비합니다.",
        "3. 에어파스를 한 손으로 잡습니다.",
        "4. 다른 손으로 에어파스 뚜껑을 잡습니다.",
        "5. 뚜껑을 잡은 손을 위로 당겨 뚜껑을 열어줍니다.",
        "6. 에어파스 몸통을 잡은 손의 검지로 분사하는 곳을 잡아줍니다.",
        "7. 아픈 부위(환부) 가까이 에어파스를 위치하고 검지를 접어 에어파스를 분사합니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/Using%20Airpas%20(Spray)/Using_Airpas(Spray)_7.png"]'),
        ('밴드 붙이기', 'daily_life', 0, 0,
        '["1. 밴드를 준비합니다.",
        "2. 여러 개가 있다면 하나를 떼어냅니다.",
        "3. 밴드를 가로 방향으로 놔둡니다.",
        "4. 밴드 포장 끝을 잡고 뜯습니다.",
        "5. 포장 속에 들어있는 밴드를 꺼내서 뒤집습니다.",
        "6. 밴드 뒷면의 포장부분을 하나씩 뜯어냅니다.",
        "7. 포장 부분을 다 뜯어냈다면 다시 뒤집습니다.",
        "8. 끈적거리는 부분으로 상처부위에 감아줍니다.",
        "9. 상처부위를 완전히 덮어서 밴드를 감아줍니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/band/band1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/band/band9.png"]'),
       ('3분 카레 만들기', 'cooking', 0, 0,
        '["1. 3분 카레, 크린 랩, 밥, 전자레인지를 준비합니다.",
        "2. 카레 포장 박스를 뜯습니다.",
        "3. 카레 포장 팩을 꺼냅니다.",
        "4. 카레 포장 팩을 뜯습니다.",
        "5. 준비된 밥 위에 카레를 부어줍니다.",
        "6. 랩을 카레밥위에 씌워줍니다.",
        "7. 랩이 떨어지지 않도록 눌러서 고정합니다.",
        "8. 전자레인지를 열어줍니다.",
        "9. 시간을 설정하고 시작버튼을 눌러줍니다.",
	    "10. 시간이 다 끝나면 열어서 보호 장갑을 끼고 꺼내줍니다.",
	    "11. 랩을 벗깁니다.",
	    "12. 만들어진 카레를 맛있게 먹습니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/curry/curry1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry9.png",
 	    "https://storage.googleapis.com/example-gurdening-com/img/curry/curry10.png",
	    "https://storage.googleapis.com/example-gurdening-com/img/curry/curry11.png",
        "https://storage.googleapis.com/example-gurdening-com/img/curry/curry12.png"]'),
        ('손씻기', 'cleanliness', 0, 0,
        '["1. 씻을 손이 있습니다.",
        "2. 수전을 열어 물이 나오게 합니다.",
        "3. 손에 물을 묻히고 비누를 문질러 거품을 나게 합니다.",
        "4. 흐르는 물에 손을 문질러 거품이 안 나올 때까지 씻습니다.",
        "5. 손을 다 씻었으면 수전을 닫습니다.",
        "6. 손을 수건에 닦아 물기를 제거합니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash8.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash9.png",
	    "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash10.png",
        "https://storage.googleapis.com/example-gurdening-com/img/handwash/handwash11.png"]'),
        ('마스크 쓰기', 'daily_life', 0, 0,
        '["1. 미세먼지 마스크를 준비합니다.",
        "2. 마스크 포장지를 뜯습니다.",
        "3. 마스크를 꺼냅니다.",
        "4. 마스크의 양 줄 끝을 잡습니다.",
        "5. 마스크를 펼칩니다.",
        "6. 먼저 한 쪽 귀에 마스크 줄을 겁니다.",
        "7. 나머지 한 쪽 귀에 마스크 줄을 겁니다.",
        "8. 코받침을 조정해 마스크를 밀착시킵니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/mask/mask1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask7.png",
        "https://storage.googleapis.com/example-gurdening-com/img/mask/mask8.png"]'),
        ('물파스 바르기', 'treatment', 0, 0,
        '["1. 물파스를 준비합니다.",
        "2. 물파스 포장지를 뜯습니다.",
        "3. 물파스를 꺼냅니다.",
        "4. 물파스 뚜껑을 돌립니다.",
        "5. 물파스 뚜껑을 제거합니다.",
        "6. 물파스 바를 부위를 준비합니다.",
        "7. 환부에 물파스를 문질러 발라줍니다."]',
        '["https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars1.png",
        "https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars2.png",
        "https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars3.png",
        "https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars4.png",
        "https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars5.png",
        "https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars6.png",
        "https://storage.googleapis.com/example-gurdening-com/img/waterpars/waterpars7.png"]');